
version: "3.8"

services:

  backend:
    build: .
    ports:
      - "2000:2000"
    volumes:
      - app-data:/app/logs
    networks:
      - app-net


volumes:
  app-data:
networks:
  app-net:
    driver: bridge